### ISSUE TITLE
[question] jwt decode on gcc 10 is throwing an error at build

### ISSUE THREAD

**Issue by RaresAil** [Thalhammer/jwt-cpp#201] opened 2022-01-25 14:44 UTC
**Describe the impediment**
I am trying the decode method form the example, but on build i get this error

```
couldn't deduce template parameter 'json_traits'
```
and this
```
no matching function for call to 'decode(std::string*)
```

**Trying to obtain**
The code implementation which needs attention.

**Desktop (please complete the following information):** (Include/Attach if Applicable)
 - OS: MacOS Monterey 12.1
 - Compiler gcc
 - Version 10.3.1 arm-none eabi

**Additional context**
```cpp
  std::string token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE";
  auto decoded = jwt::decode(token);
```

**Logs** (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[build] /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp: In function 'int main()':
[build] /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp:41:36: error: no matching function for call to 'decode(std::string*)'
[build]    41 |   auto decoded = jwt::decode(&token);
[build]       |                                    ^
[build] In file included from /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp:14:
[build] /Users/rares/Documents/Projects/pico/esp8266-template/include/jwt-cpp/jwt.h:3596:27: note: candidate: 'template<class json_traits, class Decode> jwt::decoded_jwt<json_traits> jwt::decode(const typename json_traits::string_type&, Decode)'
[build]  3596 |  decoded_jwt<json_traits> decode(const typename json_traits::string_type& token, Decode decode) {
[build]       |                           ^~~~~~
[build] /Users/rares/Documents/Projects/pico/esp8266-template/include/jwt-cpp/jwt.h:3596:27: note:   template argument deduction/substitution failed:
[build] /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp:41:36: note:   candidate expects 2 arguments, 1 provided
[build]    41 |   auto decoded = jwt::decode(&token);
[build]       |                                    ^
[build] In file included from /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp:14:
[build] /Users/rares/Documents/Projects/pico/esp8266-template/include/jwt-cpp/jwt.h:3608:27: note: candidate: 'template<class json_traits> jwt::decoded_jwt<json_traits> jwt::decode(const typename json_traits::string_type&)'
[build]  3608 |  decoded_jwt<json_traits> decode(const typename json_traits::string_type& token) {
[build]       |                           ^~~~~~
[build] /Users/rares/Documents/Projects/pico/esp8266-template/include/jwt-cpp/jwt.h:3608:27: note:   template argument deduction/substitution failed:
[build] /Users/rares/Documents/Projects/pico/esp8266-template/main.cpp:41:36: note:   couldn't deduce template parameter 'json_traits'
[build]    41 |   auto decoded = jwt::decode(&token);
[build]       |                                    ^
```

</details>

**Comment by prince-chrismc** [comment] 2022-01-25 16:21
Can you please share what commit you are using and the includes you are using? 🙏 

I very recently played with this so I want to make sure I know exactly where to look so we can resolve this quickly!

**Comment by RaresAil** [comment] 2022-01-25 16:48
I am using the commit from 10 hours ago 97c8782605570c45b15183a270b39d16323068e8 and i am using the `jwt-cpp` folder, i already have the json one with version `3.10.5`

**Comment by RaresAil** [comment] 2022-01-25 16:52
Also, i am not sure i am importing the OpenSSL correctly, i have like this but when i try to use anything from it i have this error: `undefined reference to "method's name`

```
target_include_directories(${PROJECT_NAME} PUBLIC ${CMAKE_SOURCE_DIR}/include)
target_compile_options(${PROJECT_NAME} PUBLIC "-Wno-psabi")

target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_SOURCE_DIR}/src)

set(OPENSSL_ROOT_DIR "/usr/local/opt/openssl")
find_package(OpenSSL REQUIRED)

target_link_libraries(${PROJECT_NAME}
  OpenSSL::SSL
)
```

**Comment by prince-chrismc** [comment] 2022-01-26 19:04
> i already have the json one with version `3.10.5`

Do you mean you are trying to use https://github.com/nlohmann/json?

> i am not sure i am importing the OpenSSL correctly

You'll want both targets https://cmake.org/cmake/help/latest/module/FindOpenSSL.html#imported-targets

https://github.com/Thalhammer/jwt-cpp/blob/3bd600762a70faccc7ec1c2dacb999cba6c6ef5e/CMakeLists.txt#L92

Since you are using CMake, how are you including JWT-CPP in your project?

***

If your project is open source, feel free to share I might see something if I can poke around 😄

**Comment by RaresAil** [comment] 2022-01-26 19:08
Hey, i added the JWT-CPP files in include, but i am not sure it will work with my type of project, is an IoT device, and to get the time i use an RTC, but i made a workaround and i implemented something similar to a JWT.

This is the repo: https://github.com/RaresAil/rpi-pico-esp-cpp

**Comment by prince-chrismc** [comment] 2022-01-26 19:21
That's an exciting project! I've never tried using this JWT-CPP for IoT so I am not sure what to expect.
I am sorry it did not work for you use case.

If the issue is no longer relevant feel free to close it :)

**Comment by RaresAil** [comment] 2022-01-26 19:22
Thank you for your help 😄

**Comment by Thalhammer** [comment] 2022-01-26 20:02
I'd like to reopen this. 
ESP SDK Supports wolfSSL and Exceptions so we should be able to support it (that said I think we should get a noexcept mode done at some time in the future).
The error you are seeing is because you tried to pass a pointer to a string to `decode`. The error log shows the line is
```cpp
auto decoded = jwt::decode(&token);
```
Removing the `&`, so it reads like the example you posted should fix the error.

**Comment by RaresAil** [comment] 2022-01-26 22:14
I am not using ESP SDK, the IoT project is made from 0, and i already implemented a custom functionality for HS256 signing 😞

**Closed** 2022-01-31 09:59 UTC
Labels: question
