### ISSUE TITLE
comparison always false (-Wtype-limits)

### ISSUE THREAD

**Issue by Xipiryon** [Thalhammer/jwt-cpp#12] opened 2018-11-28 15:59 UTC
Hi !
Just in case you missed it, compiling with gcc with `-Wtype-limits` produces the following warning:

```
jwt-cpp/jwt.h: In static member function ‘static std::unique_ptr<bignum_st, void (*)(bignum_st*)> jwt::algorithm::ecdsa::raw2bn(const string&)’:
jwt-cpp/jwt.h:269:15: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if(raw[0] >= 0x80) {
```
I don't know if it's relevant in the way computations are done, but maybe you could be interested :)

**Comment by Thalhammer** [comment] 2018-11-28 16:02
This has already been pointed out in #10 and is fixed in the current master. And yes I did indeed miss it :)
Please check if the problem is still there if you use the most recent commit.

**Closed by Thalhammer** 2018-11-28 16:02 UTC
